### ISSUE TITLE
how make style work only with mounted component

### ISSUE THREAD

**Issue by craigcosmo** [webpack-contrib/style-loader#141]
car.css

``` css
div{ color: blue}
```

boat.css

``` css
div{color:red}
```

Car.js component

``` jsx
import React from 'react'
import 'car.css'
export default class Car extends React.Component {
    render() {
        return (
            <div>car</div>
        )
    }
}
```

Boat.js component

``` jsx
import React from 'react'
import 'boat.css'
export default class Boat extends React.Component {
    render() {
        return (
            <div>boat</div>
        )
    }
}
```

I have boat.js and car.js component. If car component is mounted, style will insert to header of document. Which make the div color global.

If boat component is mounted, same thing happen. Now, I unmount boat component. But the style tag is still there in the header. That makes my div in car component `red` color, it's was supposed to be `blue`. So, is there way to insert style tag within the component instead of header? so when it's unmounted the style will be gone as well.

**Comment by larsnystrom** [comment]
Looks like you want to use [css-modules](https://github.com/css-modules/css-modules) and the webpack [css-loader](https://github.com/webpack/css-loader).

**Comment by michael-ciniawsky** [comment]
@craigcosmo Please @larsnystrom has stated out take a look at CSSModules to avoid global styles in your component based architecture all together. `css-loader` has this build in
`{ loader: 'css-loader', options: { modules: true } }`

**Comment by adomoshe** [comment]
Hey, I just had this same problem with the css files overriding eachother when mounting different pages using React Router. I came up with the following:

`import React, { Component } from 'react';

class Hangman extends Component {
...
  componentWillMount() {
    require('../../assets/css/Hangman.css')
  }
...
}`

I am new to development and definitely to React so please feel free to correct me here, but I figured this issue was arising during runtime when all global code is run and both of my component files are importing their css.

Requiring the css when the component will mount (so when React Router serves it) seems to prevent this by specifying to require the css only when the component is served. For some reason import doesn't work here but require did.

This solution seems to work for now, I hope this helps and if someone has a better explanation for the inner workings please share!

**Comment by sahilchopra** [comment]
Any solution for this?

**Comment by hellohejinyu** [comment]
With the rise of Tailwind CSS, many class names like `m-0` and `m-1` have appeared in CSS. At this point, the issue with `style-loader` can cause styles to interfere between components. For example, one component might use `m-0` to reset the margin and then add a `margin-right` (`mr-1`). The insertion of styles from another component could then cause CSS priority changes, leading to unexpected styles.
