### ISSUE TITLE
style-loader modules adds ~27kb to bundle.js?

### ISSUE THREAD

**Issue by royair** [webpack-contrib/style-loader#200]
I've created a simple webpack 2 project with plain html file + index.js with an import to an empty .css.
then ran webpack with `-p --env=production`

it seem that although uglification (is that a word?) and minification the end result weigh more 28kb!
when commenting out the import .css statement  - bundle.js returned to a more adequate 1kb size.

is it normal for style-loader to add a 27kb to a production state bundle?

thanks in advance.

**Comment by michael-ciniawsky** [comment]
This is a known issue atm, `style-loader && css-loader` require the `Buffer` polyfill for sourcemaps, a bit of overhead is normal during the fact that `style-loader`  adds it's logic to the bundle. For production I highly recommend using `extract-text-webpack-plugin`(parallel loading of CSS/JS) + removed webpack specifics in th CSS.For development try

**webpack.config.js**
```js
node: {
  buffer: false
}
```

Feel free to reopen if the regression persists nevertheless 😛

**Comment by stonebk** [comment]
Note it should be uppercase "B":

    node: {
        Buffer: false
    }

**Comment by rosenfeld** [comment]
@stonebk, could this issue be reopened, please?

Passing `node: false` or `node: {Buffer: false}` doesn't significantly change the overhead. Using `extract-text-webpack-plugin` is often not desired when creating SPA's using client-side routing, since the initial CSS would be minimal and the remaining ones would be loaded as needed, in combination with lazy loading techniques. If we extract all CSS in a single CSS file to be loaded in the initial page it could become too large, becoming a bigger problem than the overhead of style-loader and css-loader.

In those cases the main problem is that every lazily loaded module making use of CSS loaded files would be affected by the overhead. Wouldn't it be possible to only load the code with the overhead once in a "vendors" entry point or something like that instead of paying for that overhead in every lazily loaded module where CSS is imported?

**Comment by stonebk** [comment]
@rosenfeld I have no control over the ticket or the project, I was just correcting the property name for the configuration. You might want to open a new ticket.

**Comment by rosenfeld** [comment]
Oh, sorry, that's right, I intended to mention @michael-ciniawsky instead. Michael, would you mind reopening the ticket?

**Comment by rosenfeld** [comment]
Please ignore my comments. I just noticed that my webpack setup was incorrect and that the commons-chunk plugin wasn't set up correctly. Now that I fixed it I can confirm that the overhead can be added only to the commons chunk as I was expecting it to.
