### ISSUE TITLE
Feature request: Prevent duplicate injection of CSS into the dom

### ISSUE THREAD

**Issue by terencechow** [webpack-contrib/style-loader#205]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I have Repo A which imports components from Repo B. Both Repo A and Repo B use CSS modules and use bootstrap-css (a css_modules compatible bootstrap). When I do something like `composes: btn from bootstrap-css/lib/buttons;` in Repo A, it doesn't matter how many files I do that in, that buttons css file gets injected into the dom only once. (I see the `link:blob` only once in chrome). However if Repo B has a component with `composes: btn from bootstrap-css/lib/buttons;` and Repo A uses that component, what ends up happening is that the css file for `bootstrap-css/lib/buttons` is injected twice, once due to Repo A using it, and once due to the Repo B component using it.

Is there a way to prevent this duplication of css? I was thinking something along the lines of hashing the css file and comparing hashes of prior imports before importing any css. 

Note: if this is something that should be done at the webpack level I can make the request there and not in style-loader...

**What is the expected behavior?**
CSS should not be duplicated

**If this is a feature request, what is motivation or use case for changing the behavior?**
I do not want duplicate css

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack 2.2, Node 6.5, mac OSX

**Comment by michael-ciniawsky** [comment]
@terencechow One starting point could be [here](https://github.com/webpack-contrib/css-loader/blob/master/lib/css-base.js), `css-loader` doesn't just export a `{String}` => `[id, [css.content, css.map, css.locals ]]` which style loader uses to avoid duplicates, but this is in any case a more tricky request and I need more info, like a test repo and can't guarantee anything yet how and where this needs to be adressed 😛

**Comment by michael-ciniawsky** [comment]
Normally the `style-loader` dedupes CSS based on the format I posted in the comment above. I need more info about your setup to see what might be possible, I close the issue until more info is provided, feel free to reopen any time :)

**Comment by adi518** [comment]
How did you resolve this? I have a similar issue, where different apps, which bundle the same ui library inject the same style. I made haste to `style-loader` docs, thinking the `insert` may provide a content hash parameter I can use in runtime, but it doesn't, so I have to calculate the hash on runtime, which heavy and unnecessary.

**Comment by crobinson42** [comment]
@adi518 what was your solution? I'm in the same position.

**Comment by adi518** [comment]
@crobinson42 There was no ready-made solution because `style-loader` caters to a single app, not many. Alternatively, we can call these micro-frontends. So the solution was to build a Webpack plugin that takes care of style insertion (instead of using the default style insertion) and use it on every app/library within the eco-system of the company, this way we get control over the injection of every style sheet, no matter the source. In addition to that, I had to write another small plugin, which takes the final CSS output and prepends it with a `/* content-hash: #... */` comment. This way, I was able to read the content-hash of each stylesheet ,store it in a runtime cache (e.g., a `Map` object) and avoid injecting it again once it was injected.

**Comment by crobinson42** [comment]
@adi518 Thanks - that's the rabbit whole I've gone down as well except for rollup.js 👌🏻. It's very surprising this isn't a larger issue in the community.

**Comment by adi518** [comment]
Here's a PostCSS plugin to get you started:

```js
// https://github.com/postcss/postcss-plugin-boilerplate/

const postcss = require('postcss');
const CryptoJS = require('crypto-js');

module.exports = postcss.plugin('content-hash', function() {
  return function(root) {
    const contentHash = CryptoJS.MD5(root.source.input.css);
    root.prepend({ text: `content-hash:${contentHash}` });
  };
});
```

You may need to alter it since the plugin API changed a bit between some versions of PostCSS.

The other plugin, which takes care of insertion is a `style-loader` plugin. Aside from collating all injections through the same function, you can leverage it to add things like version attributes, which helps other developers look at the code and figure out the package name and version that the style sheet belongs to. 👍

**Comment by crobinson42** [comment]
@adi518 Thanks! I have a faster hashing function that doesn't use crypto-js, I wonder if that is important:

```
function hashCode(str) {
    for(var i = 0, h = 0; i < s.length; i++)
        h = Math.imul(31, h) + s.charCodeAt(i) | 0;
    return h;
}
```

**Comment by adi518** [comment]
I tried a few of them and settled for a package and the MD5 standard, but that might be fine. Since it's all done in build-time, it may not be that important, unless, it bottlenecks the build somehow.
