### ISSUE TITLE
unuse/unref doesn't seem to working

### ISSUE THREAD

**Issue by EvNaverniouk** [webpack-contrib/style-loader#50]
I can't seem to be able to get `unuse()` to remove the style from the page. Calling `use()` correctly loads the style, but calling `unuse()` doesn't remove it.

My loaders are setup as such:

```
{test: /\.css$/, loader: 'style!css'},
{test: /\.less$/, loaders: [
    "style-loader",
    "css-loader",
    "less-loader"
]},
```

And my code looks like this:

```
var style = require('style/useable!./../less/themes/' + this.state.theme + '.less');
style.use(); // This works
style.unuse(); // This doesn't work
```

Any idea what could be going wrong?

**Comment by globexdesigns** [comment]
I was able to get around my issue by setting the `style/useable!` prefix in the loader definition instead of in my code:

My new loader definition is:

```
{test: /\.css$/, loader: 'style!css'},
{test: /\.less$/, loaders: [
    "style/useable",
    "css",
    // Fix for LESSHat
    require.resolve("./../css-fix-loader.js"),
    "less"
]},
```

This seems to make `unuse` work correctly, but it also means all my styles now need to call `use()` even if I don't want them to be dynamically loaded. This is less than ideal so I'm keeping this issue open.

**Comment by johnnyji** [comment]
Great solution! This will come in handy for me at work :)
