### ISSUE TITLE
hot reload doesn't work with local styles

### ISSUE THREAD

**Issue by bloodyowl** [webpack-contrib/style-loader#66]
it seems like it's wished, given that line https://github.com/webpack/style-loader/blob/master/useable.js#L32

why was the problem that made you put these conditions?

**Comment by bloodyowl** [comment]
(precision: I'm using the `useable` API)

**Comment by sokra** [comment]
As CSS with locals **export** stuff (the locals) from the CSS it behave different than standard CSS (which **only** has side-effects).

Modules with exports need to be accepted by the importing module. See [HMR spec](http://webpack.github.io/docs/hot-module-replacement.html).

It's because the locals could change between updates.

``` js
var styles = require("./style.css");

if(modules.hot) {
  module.hot.accept("./style.css", function() {
    styles = require("./style.css");
  });
}
```

For usable styles you need to `unref` the old style (theoretically, but in fact it's disposed anyway) and `ref` the new style.

**Comment by vjpr** [comment]
I'm seeing the same problem. My locals looks like this:

```
locals: Object
dispose: "_3scgUmhwK3igSWVJk7i5js"
exports: "_3tbKKgqfHBaB61oMOBnJV2"
hot: "_1SLXKHwdtLwnEd6-KId_IG"
id: "_3ZNsMYDJXmeZkU1qRRbytg"
locals: "_3QgOLcgn2yoyKsGpnP0zhG"
```

When it should return my css class names.

**Comment by vjpr** [comment]
I think it might be a bug in css-loader actually...

**Comment by vjpr** [comment]
...and now it has just started working! Must have been a caching problem.

I was doing `require('css?module!./index.css')`, and then had the loaders from `webpack.config` running twice which was causing the problem.

**Comment by hackwaly** [comment]
Since the `.locals` object is a plain JSON object. we can store the last `.locals` and compare it with the incoming hot module's `.locals`. If they are structural equal. we can consider it has no side effect then `accept()` it.

**Comment by michael-ciniawsky** [comment]
@hackwaly Could you propose your comment via PR 😛 ?
